import type { Metadata } from "next";
import "./globals.css";
import DashboardLayout from "@/layout/Layout";
import StyledComponentsRegistry from "@/lib/registry";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <Providers>
        <StyledComponentsRegistry>
        <DashboardLayout>{children}</DashboardLayout>
        </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
